version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 8088:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
